version: '2'

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "100m"
    max-file: "10"
    tag: "{{.ImageName}}|{{.Name}}"

x-deploy: &default-deploy
  resources:
    limits:
      cpus: '0.50'
      memory: 512M
    reservations:
      cpus: '0.25'
      memory: 128M

services:
  app_python:
    image: azazkamaz/tmp_inno_devops_labs:app_python-latest
    ports:
      - 8080:8080
    logging: *default-logging
    deploy: *default-deploy

  grafana:
    image: grafana/grafana:9.3.1
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
      - ./config/grafana-datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=adminadmin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    ports:
      - 3000:3000
    logging: *default-logging
    deploy: *default-deploy

  promtail:
    image: grafana/promtail:2.7.1
    command: '-config.file=/etc/promtail/config.yaml'
    restart: unless-stopped
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - promtail-data:/var/lib/promtail/positions
      - ./config/promtail.yml:/etc/promtail/config.yaml
    ports:
      - 9080:9080
    logging: *default-logging
    deploy: *default-deploy

  loki:
    image: grafana/loki:2.7.1
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped
    ports:
      - 3100:3100
    logging: *default-logging
    deploy: *default-deploy

  prometheus:
    image: prom/prometheus:v2.40.6
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=5d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    logging: *default-logging
    deploy: *default-deploy

volumes:
  grafana-data:
  loki-data:
  promtail-data:
  prometheus-data: