name: app_python docker build and upload

on:
  push:
    branches:
      - lab3

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Docker
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:app_python"
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/tmp_inno_devops_labs:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/tmp_inno_devops_labs:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/tmp_inno_devops_labs:buildcache,mode=max